# Aigisはこの設定ファイルが存在するディレクトリと同じディレクトリから実行されます
# すべてのパスはそこからの相対パスでなければなりません
name: AmiTemplate Styleguide

# 再帰的に解析するソースファイルを含むディレクトリ
source:
  - ../public/lib/_scss/
# 複数のディレクトリを指定することもできます
# source:
#  - ./sass
#  - ./sass/style.scss

# aigisがコメントを文書化するためにスキャンするタイプ
source_type:
#  - .css
#  - .sass
  - .scss
#  - .styl

# マークダウンから文書を生成したい場合
# source_type: .md

# aigisが構築するディレクトリ
dest: ../public/_styleguide

# ドキュメントを構築するために必要なアセット
# ドキュメント関連のアセットもここに置くことができます：イメージ、CSSなど
dependencies:
  - ./aigis_assets
  - ../public/lib/css/styles.css

# マークダウンファイルから作成されたインデックスページ
#index: ./index.md

# テンプレートエンジンを選択できます：ejs、jade、handlebars
template_engine: jade

# ページを生成するためのテンプレートファイルを含むディレクトリ
# 'layout.xxx'と 'index.xxx'（.ejsまたは.jadeまたは.hbs）を含む必要があります。
template_dir: ./template_jade

# Aigisがログを表示する
log: false

# カラーパレットページ（color.html）が不要な場合は、falseを設定することができます
color_palette: true

#
transform:
  - html
#  - jade
#  - ejs
#  - hbs
#  - coffee

# Aigis
timestamp_format: 'YYYY/MM/DD HH:mm'

preview_class: aigis-preview

component_dir: ./html

output_collection:
  - category
  - tag

highlight: true
highlight_theme: monokai
lang_prefix: 'language-'

# plugin directory
# plugin: ./plugin

helper_options:
  disable_link_index: true
